Repository fe11-part2-team8/openmind, pull requests merged in 2024-10, with the labels that each got.

#6 [Feat] API 및 글로벌 스타일 셋업 #5
  src/App.js
  src/api.js
  src/global.css
Labels: feature

#11 [FEAT] 질문 입력 폼 및 모달 구현 #8
  src/Main.jsx
  src/assets/images/ic_close.svg
  src/assets/images/ic_message.svg
  src/assets/images/keeping
  src/assets/images/test_profile.svg
  src/components/QuestionCreateModal/QuestionCreateModal.module.css
  src/components/QuestionCreateModal/index.jsx
  src/components/keeping
Labels: feature

#13 [FEAT, FIX, REFACTOR] API 로직 수정, 커스텀 훅 제작
  src/App.js
  src/api.js
  src/hooks/keeping
  src/hooks/useAsync.js
Labels: feature, invalid

#17 [FEAT] 페이지네이션 - Feature/#16 pagination
  package-lock.json
  package.json
  public/index.html
  src/components/QuestionCreateModal/index.jsx
  src/global.css
  src/pages/SubjectList.page.jsx
Labels: feature

#12 [FEAT] 피드 생성을 위한 입력 폼 #4
  src/App.js
  src/assets/datas/profile/index.js
  src/assets/datas/profile/profileImages/bear-smile.png
  src/assets/datas/profile/profileImages/cat-bee.png
  src/assets/datas/profile/profileImages/cat-smile.png
  src/assets/datas/profile/profileImages/dog-hone.png
  src/assets/datas/profile/profileImages/dog-smile.png
  src/assets/datas/profile/profileImages/hamster.png
  src/assets/datas/profile/profileImages/music-band-bass.png
  src/assets/datas/profile/profileImages/music-band-guitar.png
  src/assets/datas/profile/profileImages/pig.png
  src/assets/datas/profile/profileImages/rabbit-smile.png
  src/components/SubjectCreateForm/index.jsx
Labels: feature

#24 [Feat] 공통 버튼 - #22 feat common button
  src/assets/images/icon-arrow-right.svg
  src/global.css
  src/pages/SubjectList.page.jsx
Labels: feature

#26 [fix] 서브젝트 생성 시 로컬 스토리지에 id가 저장되지 않던 오류 수정 #25
  src/assets/datas/profile/index.js
  src/assets/datas/profile/profileImages/bear-smile.png
  src/assets/datas/profile/profileImages/cat-bee.png
  src/assets/datas/profile/profileImages/cat-smile.png
  src/assets/datas/profile/profileImages/dog-hone.png
  src/assets/datas/profile/profileImages/dog-smile.png
  src/assets/datas/profile/profileImages/hamster.png
  src/assets/datas/profile/profileImages/music-band-bass.png
  src/assets/datas/profile/profileImages/music-band-guitar.png
  src/assets/datas/profile/profileImages/pig.png
  src/assets/datas/profile/profileImages/rabbit-smile.png
  src/components/SubjectCreateForm/index.jsx
Labels: bug

#31 [Feat] 서브젝트 리스트 페이지 디자인 #28
  public/favicon.svg
  src/assets/images/icon-message.svg
  src/components/QuestionCreateModal/index.jsx
  src/global.css
  src/pages/SubjectList.page.jsx
  src/pages/SubjectList.page.module.css
Labels: feature

#32 [FEAT, FIX] 개별 피드 페이지 제작, NotFound 페이지 제작, useAsync 수정, 유저플로우 변경
  package-lock.json
  package.json
  public/favicon.svg
  public/index.html
  public/snsLink.png
  src/App.js
  src/Main.jsx
  src/assets/images/banner.png
  src/assets/images/empty.png
  src/assets/images/facebookShare.png
  src/assets/images/kakaoShare.png
  src/assets/images/urlShare.png
  src/assets/images/warning.png
  src/components/SubjectCreateForm/index.jsx
  src/global.css
  src/hooks/useAsync.js
  src/pages/NotFound.jsx
  src/pages/PostPage.jsx
  src/pages/PostPage.module.css
  src/pages/SubjectList.page.jsx
Labels: bug, feature

#37 수정: 버튼 텍스트 정렬 수정
  src/global.css
Labels: bug

#38 [Feat] 답변 입력 폼 #14
  package-lock.json
  src/Main.jsx
  src/components/AnswerCreateForm/AnswerCreateForm.module.css
  src/components/AnswerCreateForm/index.jsx
Labels: feature

#35 [CHORE] 환경변수 설정 #34
  package-lock.json
  package.json
  src/api.js
  src/pages/PostPage.jsx
Labels: feature

#43 [Feat] 로딩 컴퍼넌트 #39
  package-lock.json
  src/components/Loading/Loading.module.css
  src/components/Loading/index.jsx
  src/global.css
  src/pages/SubjectList.page.jsx
  src/pages/SubjectList.page.module.css
Labels: bug, feature

#42 [Feat] 질문 생성 모달 렌더링 #40
  src/Main.jsx
  src/components/QuestionCreateModal/QuestionCreateModal.module.css
  src/components/QuestionCreateModal/index.jsx
  src/pages/PostPage.jsx
Labels: feature

#30 [Feat] 질문 리스트 아이템 #18
  package-lock.json
  package.json
  src/Main.jsx
  src/assets/images/ic_Edit.svg
  src/assets/images/ic_More.svg
  src/assets/images/ic_thumbs-down.svg
  src/assets/images/ic_thumbs-up.svg
  src/components/AnswerCreateAndEdit/AnswerCreateForm.module.css
  src/components/AnswerCreateAndEdit/index.jsx
  src/components/AnswerCreateForm/AnswerCreateForm.module.css
  src/components/AnswerCreateForm/index.jsx
  src/components/QuestionListItem/Dropdown/index.jsx
  src/components/QuestionListItem/QuestionAndAnswer.jsx
  src/components/QuestionListItem/QuestionListItem.module.css
  src/components/QuestionListItem/ReactionButton.jsx
  src/components/QuestionListItem/index.jsx
  src/components/SubjectCreateForm/index.jsx
  src/pages/PostPage.jsx
Labels: feature
