Repository fe11-part2-team8/openmind, pull requests merged in 2024-11, with the labels that each got.

#48 [Feat] 메인 페이지 #41
  src/App.js
  src/Main.jsx
  src/assets/images/main-background.png
  src/pages/HomePage.jsx
  src/pages/HomePage.module.css
Labels: feature

#54 [Fix] 서브젝트 리스트 페이지 수정 #53
  src/global.css
  src/pages/SubjectList.page.jsx
  src/pages/SubjectList.page.module.css
Labels: bug

#55 [FEAT, FIX] 개별 피드 페이지 오류 및 반응형 수정
  public/index.html
  src/assets/images/facebookShare.png
  src/assets/images/facebookShare.svg
  src/assets/images/kakaoShare.png
  src/assets/images/kakaoShare.svg
  src/assets/images/messages.png
  src/assets/images/snsLink.png
  src/assets/images/urlShare.png
  src/assets/images/urlShare.svg
  src/global.css
  src/pages/HomePage.jsx
  src/pages/NotFound.jsx
  src/pages/PostPage.jsx
  src/pages/PostPage.module.css
  src/pages/SubjectList.page.jsx
Labels: bug, feature

#56 [Fix] 질문 카드에 대한 오류 수정 #50
  src/assets/images/ic-rejected.svg
  src/components/AnswerCreateAndEdit/AnswerCreateAndEdit.module.css
  src/components/AnswerCreateAndEdit/index.jsx
  src/components/QuestionList/Dropdown.jsx
  src/components/QuestionList/QuestionItem.jsx
  src/components/QuestionList/QuestionList.module.css
  src/components/QuestionList/ReactionButton.jsx
  src/components/QuestionList/index.jsx
  src/components/QuestionListItem/QuestionAndAnswer.jsx
  src/components/QuestionListItem/ReactionButton.jsx
  src/components/QuestionListItem/index.jsx
  src/pages/PostPage.jsx
  src/utils/day.js
Labels: bug, invalid

#57 [Fix][Feat] 답변 입력 폼 오류와 메인페이지 수정 #51
  src/assets/images/main-background-m.png
  src/pages/HomePage.jsx
  src/pages/HomePage.module.css
Labels: bug, feature

#58 [FIX] 삭제하기 버튼 디자인 변경
  src/pages/PostPage.jsx
  src/pages/PostPage.module.css
Labels: bug

#59 [Feat] 서브젝트 리스트 페이지 및 공통 요소 #53
  src/App.js
  src/components/Loading/Loading.module.css
  src/global.css
  src/pages/SubjectList.page.jsx
Labels: feature

#60 [Fix] 질문 생성 모달 오류 해결 #49
  src/components/QuestionCreateModal/index.jsx
  src/components/QuestionList/QuestionItem.jsx
Labels: bug, invalid

#65 [Fix] 질문 카드, 답변 카드 오류 수정 #62
  src/components/AnswerCreateAndEdit/index.jsx
  src/components/QuestionList/Dropdown.jsx
  src/components/QuestionList/QuestionItem.jsx
  src/components/QuestionList/QuestionList.module.css
Labels: bug, invalid

#66 [Feat, Fix] 서브젝트 리스트 페이지 추가 및 수정 - Feature/#64 subjectlist
  src/pages/SubjectList.page.jsx
Labels: bug, feature

#67 [Fix] 메인페이지 버그 수정 #61
  src/components/AnswerCreateAndEdit/index.jsx
  src/components/SubjectCreateForm/SubjectCreateForm.module.css
  src/components/SubjectCreateForm/index.jsx
  src/pages/HomePage.jsx
  src/pages/HomePage.module.css
Labels: bug, feature, invalid

#69 [FIX] 개별 피드 페이지 오류 수정
  src/api.js
  src/pages/PostPage.jsx
Labels: bug

#70 [Feat] 질문 생성 모달 개선 #63
  src/components/QuestionCreateModal/QuestionCreateModal.module.css
  src/components/QuestionCreateModal/index.jsx
Labels: feature, invalid

#74 [Feat] Device Type Context와 Debounce 커스텀 훅 구현 #73
  src/App.js
  src/contexts/DeviceTypeContext.js
  src/contexts/keeping
  src/hooks/useDebounce.js
Labels: feature

#78 [Fix] 메인페이지 이름 입력 박스 반응형 수정 #77
  src/components/SubjectCreateForm/SubjectCreateForm.module.css
  src/components/SubjectCreateForm/index.jsx
  src/pages/HomePage.module.css
Labels: bug

#80 [Feat] 이름 입력 폼 trim()추가 #79
  src/components/SubjectCreateForm/index.jsx
Labels: feature
